# Generated by Django 4.1 on 2022-08-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트 캠퍼스 사용자', 'verbose_name_plural': '패스트 캠퍼스 사용자'},
        ),
    ]
